export const APP_ACTIONS = {
  REQUEST_BACK_PAGE_ACTION: 'APP.REQUEST_BACK_PAGE_ACTION',
  SPLASH_SCREEN: 'APP.SPLASH_SCREEN',
  LOGIN_PAGE: 'APP.LOGIN',
};

export const USER_ACTIONS = {
  REQUEST_CHECK_EXISTED_USER: 'APP.REQUEST_CHECK_EXISTED_USER',
  REQUEST_LOGIN: 'APP.REQUEST_LOGIN',
  REQUEST_LOGIN_SUCCESS: 'APP.REQUEST_LOGIN_SUCCESS',
  REQUEST_LOGIN_FAILURE: 'APP.REQUEST_LOGIN_FAILURE',
};

